### ISSUE TITLE
Kategorie Pruef-und-Wartungsplaketten funktioniert nicht

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#25]
https://shop.feuerschutz.ch/produkt-kategorie/pruef-und-wartungsplaketten/pruefplaketten/1

**Comment by Tyratox** [comment]
Grund: Produkt jahresplakette-jahreszahl-4-stellig-jahresfarbe hat kein Bild. Wird jetzt einfach nicht mehr angezeigt.
