### ISSUE TITLE
Lieferkosten von 12.50 werden in der Bestätigung nicht immer angezeigt

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#27]
Kann evtl. beim Checkout die Zahlungsmethode "Rechnung" bei gewissen Browsern rausgeklickt werden? In der Bestellungsübersicht im Backend sind die Lieferkosten von 12.50 jeweils auch nicht drin.

<img width="1079" alt="bildschirmfoto 2018-09-17 um 13 55 28" src="https://user-images.githubusercontent.com/42411789/45621928-871ade80-ba82-11e8-9619-ba121e7ce9f2.png">

**Comment by Tyratox** [comment]
Hmm komisch, ich setze den Zahlungstyp manuell auf "feuerschutz_invoice", ich beachte dabei die Checkbox gar nicht.
