### ISSUE TITLE
Preisanzeige sobald alle Optionsfelder, ausser der Texteingabe, ausgefüllt sind.

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#30]
https://shop.feuerschutz.ch/produkt/parkplatzschild-mit-wunschtext
https://shop.feuerschutz.ch/produkt/parkplatzschild-mit-wunschtext-reflektierend
https://shop.feuerschutz.ch/produkt/parkverbot-mit-text-nach-wahl
https://shop.feuerschutz.ch/produkt/halteverbot-mit-text-nach-wahl
https://shop.feuerschutz.ch/produkt/parkplatzschild-mit-wunschtext-3
https://shop.feuerschutz.ch/produkt/parkplatzschild-mit-wunschtext-2
https://shop.feuerschutz.ch/produkt/verbotszeichen-mit-text-nach-wahl
https://shop.feuerschutz.ch/produkt/hinweisschild-nach-individuellen-wuenschen
https://shop.feuerschutz.ch/produkt/tragfaehigkeit-kg-mit-gewichtsangabe-nach-wunsch
evtl. weitere

Der Preis soll angezeigt sobald alle Optionsfelder, ausser der Texteingabe, ausgefüllt sind.

**Comment by Tyratox** [comment]
Wieso soll das verhalten von Textfeldern anders sein als das der Auswahlfelder?

**Comment by markus-hauser** [comment]
als kunde möchte ich den preis sehen bevor ich mich für das produkt entscheide und mit der texteingabe beginne.

**Comment by markus-hauser** [comment]
habe alle Speicher gelöscht - geht bei mir immer noch nicht?
