### ISSUE TITLE
Kommaanzeige fehlt bei Grössenangabe in der Mail-Bestätigung

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#31]
https://shop.feuerschutz.ch/produkt/safety-walk?variationId=22802

<img width="1093" alt="bildschirmfoto 2018-09-19 um 11 16 06" src="https://user-images.githubusercontent.com/42411789/45743906-6aef7c80-bbfd-11e8-96d4-a499a3410f56.png">

**Comment by Tyratox** [comment]
Normalerweise ja nicht, muss ein Fehler beim Kunden im Browser gewesen sein? Oder sieht bei euch die Bestellung immer so aus?

**Comment by Tyratox** [comment]
..?

**Comment by markus-hauser** [comment]
aktuell ist immer alles i.O. - Issue kann gelöscht werden.
