### ISSUE TITLE
Mehrfachbestellungen gleicher Menge von gleichem User

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#33]
Kann es nicht reproduzieren - Vermutung: Warenkorb unter gewissen Umständen nicht gelöscht. Ist bei registrierten Kunden wie auch Gästen schon vorgekommen.

**Comment by Tyratox** [comment]
Nachfragen wenn wir es nicht reproduzieren können!

**Comment by Tyratox** [comment]
https://github.com/hfag/shop-frontend/commit/c9aec5e90a47b8743b9db767cdb0a8bb84049305

**Comment by markus-hauser** [comment]
nicht mehr vorgekommen
