### ISSUE TITLE
Ansicht mit Einkaufswägeli/Warenkorb  in der Kopfzeile für Mobile Version

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#38]
<img width="668" alt="bildschirmfoto 2018-10-29 um 12 04 28" src="https://user-images.githubusercontent.com/42411789/47646006-df112e80-db72-11e8-8c0d-70a8c651a68e.png">

**Comment by Tyratox** [comment]
Steht etwas im Konflikt mit dem Sprachwechsler (#35). Fragt sich was wichtiger ist?
