### ISSUE TITLE
Neues Kundenkonto anlegen

### ISSUE THREAD

**Issue by markus-hauser** [hfag/shop-frontend#39]
Eine Kundin meldete folgendes Problem (ich konnte dies Rekonstruieren):
1) Login
2) Neues Kundenkonto anlegen
3) Eingabe E-Mail Adresse und Passwort
anschliessend kommt oben ein unscheinbarer Text, dass ein E-Mail gesendet wird.

dieses E-Mail sieht wie folgt aus:
<img width="1620" alt="bildschirmfoto 2018-11-12 um 15 34 40" src="https://user-images.githubusercontent.com/42411789/48353759-82dcfd00-e690-11e8-90e0-ec3a56c524e7.png">

**Die beiden Links machen für unsere Kunden keinen Sinn:**
<https://feuerschutz.ch/wp-login.php?action=rp&key=p6Mgm9yfBPGYlTOqyVr7&login=info%40taiji-aarau.ch>

https://api.feuerschutz.ch/wp-login.php

So wie es aussieht gehts anstelle in das Kundenkonto zum Passwort-Recovery-Prozess.

**Comment by Tyratox** [comment]
Die Mail soll ja auch nur zur Bestätigung sein, man kann sich direkt Anmelden nach dem Registrieren.

Kann aber den Inhalt sicherlich irgendwo anpassen. Aber das ist definitiv kein Bug und funktionieren tut die Registration trotzdem.

**Comment by markus-hauser** [comment]
Ich vermute dass die vielen Plugin-Mutationen die bei meiner letzten Prüfung vor ca. 2 Wochen noch nicht installiert gewesen waren vielleicht zu diesen Problemen geführt haben - Leider werden aktuell beim Anlegen eines Kundenkontos die scheinbar gespeicherten Daten nicht gespeichert.

**Comment by markus-hauser** [comment]
Sorry - versehentlich falschen Knopf gedrückt

**Comment by Tyratox** [comment]
Was heisst „Leider werden aktuell beim Anlegen eines Kundenkontos die scheinbar gespeicherten Daten nicht gespeichert.“?


Von: Markus Hauser <notifications@github.com>(mailto:notifications@github.com)
Antworten: hfag/shop-frontend <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 13. November 2018 at 09:27:58
An: hfag/shop-frontend <shop-frontend@noreply.github.com>(mailto:shop-frontend@noreply.github.com)
CC: Nico Hauser <me@tyratox.ch>(mailto:me@tyratox.ch), Assign <assign@noreply.github.com>(mailto:assign@noreply.github.com)
Betreff: Re: [hfag/shop-frontend] Neues Kundenkonto anlegen (#39)

**Comment by markus-hauser** [comment]
Die eingegebenen Kundendaten werden nicht hinterlegt. Ist alles leer.

**Comment by Tyratox** [comment]
es wird beim registrieren auch nur die email verlangt?! es werden aonst gar keine daten eingegeben, klar dass alles leer ist


Von: Markus Hauser <notifications@github.com>(mailto:notifications@github.com)
Antworten: hfag/shop-frontend <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 13. November 2018 at 09:43:04
An: hfag/shop-frontend <shop-frontend@noreply.github.com>(mailto:shop-frontend@noreply.github.com)
CC: Nico Hauser <me@tyratox.ch>(mailto:me@tyratox.ch), Assign <assign@noreply.github.com>(mailto:assign@noreply.github.com)
Betreff: Re: [hfag/shop-frontend] Neues Kundenkonto anlegen (#39)

**Comment by markus-hauser** [comment]
habe mich neu registriert mit mailadresse info@taiji-aarau.ch, anschliessend alle Daten wie Rechnungs- und Lieferadresse im Kundenkonto eingegeben. wenn ich unmittelbar die Daten kontrollieren will sind alle Felder wieder leer. was bleibt ist nur die mailadresse und das passwort. 

weiter kriegen gastkunden keine bestätigungs-email mehr. die bestellung kommt bei uns an die info@feuerschutz.ch rein.

**Comment by Tyratox** [comment]
Kannst du das bitte nochmals prüfen denn bei mir hat es als ich es jetzt getestet habe alles funktioniert.. wenn du eine bestehende email neu registrieren möchtest musst du den account im ganzen netzwerk (wordpress netzwerkverwaltung) löschen ansonsten ist es klar dass keine neuen mails versendet werden


Von: Markus Hauser <notifications@github.com>(mailto:notifications@github.com)
Antworten: hfag/shop-frontend <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 13. November 2018 at 11:06:58
An: hfag/shop-frontend <shop-frontend@noreply.github.com>(mailto:shop-frontend@noreply.github.com)
CC: Nico Hauser <me@tyratox.ch>(mailto:me@tyratox.ch), Assign <assign@noreply.github.com>(mailto:assign@noreply.github.com)
Betreff: Re: [hfag/shop-frontend] Neues Kundenkonto anlegen (#39)

**Comment by markus-hauser** [comment]
kam erst jetzt zum testen - funktioniert soweit alles wieder! was kleines noch: 

- der seitensprung müsste gelegentlich wieder programmiert werden.
- beim passwort zurücksetzen sollte noch ein text erscheinen, dass eine e-mail ausgelöst wurde und  es sollte anstelle des wordpress-fensters gleich direkt zurück zum Shop verlinkt werden (aktuell verlinkt der untere text  auf www.feuerschutz.ch, siehe letzten screenshot)
